# Generated by Django 3.2.7 on 2021-09-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210919_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.CharField(max_length=100),
        ),
    ]
